/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class StaxXmlObjectProjectionPlan {
  projectRows(input: Uint8Array): ObjectRowsProjectionResult
  projectRecords(input: Uint8Array): ObjectRecordsProjectionResult
}

export declare class StaxXmlStreamingEventBatchParser {
  pushChunk(chunk: Uint8Array, isFinal: boolean): StreamingEventBatch
  pushBatch(chunks: Array<Uint8Array>, isFinal: boolean): StreamingEventBatch
}

/**
 * Benchmark-oriented aggregate counters are intentionally exposed as u32.
 *
 * The public N-API shape treats these counters as modulo 2^32 values. Callers
 * that need exact counts beyond u32::MAX should partition input externally.
 */
export interface AggregateResult {
  tier: string
  inputBytes: number
  eventCount: number
  checksum: number
  attrCountTotal: number
  objectCount: number
}

export declare function createObjectProjectionPlan(spec: ObjectRowsProjectionSpec): StaxXmlObjectProjectionPlan

export declare function createStreamingEventBatchParser(): StaxXmlStreamingEventBatchParser

export interface DocumentEntityDefinition {
  entity: string
  value: string
}

export interface DocumentNodesProjectionOptions {
  autoDecodeEntities?: boolean
  addEntities?: Array<DocumentEntityDefinition>
}

export interface DocumentNodesProjectionResult {
  inputBytes: number
  nodeCount: number
  json: string
}

export interface ItemProjectionRecord {
  id: number
  name: string
  value: string
}

export interface ItemProjectionResult {
  inputBytes: number
  itemCount: number
  checksum: number
}

export interface ItemProjectionRowsResult {
  inputBytes: number
  eventCount: number
  maxDepth: number
  rows: Array<ItemProjectionRecord>
}

export interface ObjectRecordsProjectionResult {
  inputBytes: number
  eventCount: number
  maxDepth: number
  fieldCount: number
  rowCount: number
  json: string
}

export interface ObjectRowsProjectionColumn {
  present: Array<boolean>
  values: Array<string>
  numberValues: Array<number>
  spanStarts: Array<number>
  spanEnds: Array<number>
}

export interface ObjectRowsProjectionFieldSpec {
  outputName: string
  valueKind: string
  sourceKind: string
  sourceName: string
  textMode: string
}

export interface ObjectRowsProjectionResult {
  inputBytes: number
  eventCount: number
  maxDepth: number
  fieldCount: number
  rowCount: number
  columns: Array<ObjectRowsProjectionColumn>
}

export interface ObjectRowsProjectionSpec {
  itemName: string
  fields: Array<ObjectRowsProjectionFieldSpec>
}

export declare function parseAggregateBuffer(input: Buffer, tier: string): AggregateResult

export declare function parseAggregateBufferWithSimd(input: Buffer, tier: string, simd: string): AggregateResult

export declare function parseAggregateFile(path: string, tier: string): AggregateResult

export declare function parseAggregateFileWithSimd(path: string, tier: string, simd: string): AggregateResult

export declare function parseAggregateStringUtf8(input: string, tier: string): AggregateResult

export declare function parseAggregateStringUtf8WithSimd(input: string, tier: string, simd: string): AggregateResult

export declare function parseAggregateUint8Array(input: Uint8Array, tier: string): AggregateResult

export declare function parseAggregateUint8ArrayWithSimd(input: Uint8Array, tier: string, simd: string): AggregateResult

export declare function parseDocumentNodesUint8Array(input: Uint8Array, options?: DocumentNodesProjectionOptions | undefined | null): DocumentNodesProjectionResult

export declare function parseItemProjectionUint8Array(input: Uint8Array): ItemProjectionResult

export declare function parseItemProjectionViaTableUint8Array(input: Uint8Array): ItemProjectionResult

export declare function parseItemRowsViaTableUint8Array(input: Uint8Array): ItemProjectionRowsResult

export declare function parseObjectRecordsUint8Array(input: Uint8Array, spec: ObjectRowsProjectionSpec): ObjectRecordsProjectionResult

export declare function parseObjectRowsUint8Array(input: Uint8Array, spec: ObjectRowsProjectionSpec): ObjectRowsProjectionResult

export declare function parseObjectRowsViaTableUint8Array(input: Uint8Array, spec: ObjectRowsProjectionSpec): ObjectRowsProjectionResult

export declare function parseSpanTableUint8Array(input: Uint8Array): Buffer

export declare function parseStructuralIndexUint8Array(input: Uint8Array): Buffer

export interface StreamingEventBatch {
  buffer: Uint8Array
  table: Buffer
}
