/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AggregateResult {
  tier: string
  inputBytes: number
  eventCount: number
  checksum: number
  attrCountTotal: number
  objectCount: number
}

export declare function parseAggregateBuffer(input: Buffer, tier: string): AggregateResult

export declare function parseAggregateFile(path: string, tier: string): AggregateResult

export declare function parseAggregateStringUtf16(input: string, tier: string): AggregateResult

export declare function parseAggregateStringUtf8(input: string, tier: string): AggregateResult

export declare function parseAggregateUint8Array(input: Uint8Array, tier: string): AggregateResult

export declare function parseSpanTableStringUtf16(input: string): Buffer

export declare function parseStructuralIndexStringUtf16(input: string): Buffer

export declare function parseStructuralIndexUint8Array(input: Uint8Array): Buffer

export interface ItemProjectionRecord {
  id: number
  name: string
  value: string
}

export interface ItemProjectionRowsResult {
  inputBytes: number
  eventCount: number
  maxDepth: number
  rows: ItemProjectionRecord[]
}

export declare function parseItemRowsViaTableUint8Array(input: Uint8Array): ItemProjectionRowsResult
