/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'stax_xml_native.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'stax_xml_native.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = require.resolve('@stax-xml/native-wasm32-wasi-wasm32-wasi/stax_xml_native.wasm32-wasi.wasm')
  } catch {
    throw new Error('Cannot find stax_xml_native.wasm32-wasi.wasm file, and @stax-xml/native-wasm32-wasi-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports.StaxXmlObjectProjectionPlan = __napiModule.exports.StaxXmlObjectProjectionPlan
module.exports.StaxXmlStreamingEventBatchParser = __napiModule.exports.StaxXmlStreamingEventBatchParser
module.exports.createObjectProjectionPlan = __napiModule.exports.createObjectProjectionPlan
module.exports.createStreamingEventBatchParser = __napiModule.exports.createStreamingEventBatchParser
module.exports.parseAggregateBuffer = __napiModule.exports.parseAggregateBuffer
module.exports.parseAggregateBufferWithSimd = __napiModule.exports.parseAggregateBufferWithSimd
module.exports.parseAggregateFile = __napiModule.exports.parseAggregateFile
module.exports.parseAggregateFileWithSimd = __napiModule.exports.parseAggregateFileWithSimd
module.exports.parseAggregateStringUtf8 = __napiModule.exports.parseAggregateStringUtf8
module.exports.parseAggregateStringUtf8WithSimd = __napiModule.exports.parseAggregateStringUtf8WithSimd
module.exports.parseAggregateUint8Array = __napiModule.exports.parseAggregateUint8Array
module.exports.parseAggregateUint8ArrayWithSimd = __napiModule.exports.parseAggregateUint8ArrayWithSimd
module.exports.parseDocumentNodesUint8Array = __napiModule.exports.parseDocumentNodesUint8Array
module.exports.parseItemProjectionUint8Array = __napiModule.exports.parseItemProjectionUint8Array
module.exports.parseItemProjectionViaTableUint8Array = __napiModule.exports.parseItemProjectionViaTableUint8Array
module.exports.parseItemRowsViaTableUint8Array = __napiModule.exports.parseItemRowsViaTableUint8Array
module.exports.parseObjectRecordsUint8Array = __napiModule.exports.parseObjectRecordsUint8Array
module.exports.parseObjectRowsUint8Array = __napiModule.exports.parseObjectRowsUint8Array
module.exports.parseObjectRowsViaTableUint8Array = __napiModule.exports.parseObjectRowsViaTableUint8Array
module.exports.parseSpanTableUint8Array = __napiModule.exports.parseSpanTableUint8Array
module.exports.parseStructuralIndexUint8Array = __napiModule.exports.parseStructuralIndexUint8Array
