name: CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6
      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - id: setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "10.18.0"
      - id: install-deps
        name: Install dependencies
        run: pnpm install
      - id: test
        name: Run test
        run: pnpm test
